apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
    component: zookeeper
spec:
  clusterIP: None
  ports:
    - port: 2181
      protocol: TCP
  selector:
    app: zookeeper
  sessionAffinity: None
  type: ClusterIP