apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: flink-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: flink-client
  serviceName: flink-client
  template:
    metadata:
      labels:
        app: flink
        component: flink-client
    spec:
      containers:
        - name: flink-client
          image: registry.paas.psnc.pl/ecloud-poc/flink-node-poc
          imagePullPolicy: Always
          command: [ "/bin/sh","-c","while true; do sleep 5; done;" ]
          volumeMounts:
            - name: deployments
              mountPath: /deployments
            - name: log-volume
              mountPath: /opt/flink/log
            - name: jobs-config
              mountPath: /jobs-config
      volumes:
        - name: deployments
          persistentVolumeClaim:
            claimName: deployments
        - emptyDir: { }
          name: log-volume
        - secret:
            secretName: jobs-config
          name: jobs-config
