kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: flink-rolebinding
subjects:
- kind: ServiceAccount
  name: flink-sa
roleRef:
  kind: Role
  name: flink-role
  apiGroup: rbac.authorization.k8s.io
