apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-manager-checkpoints-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/job-manager-checkpoints/